version: "3.8"
services:
  app:
    build:
      context: .
      args:
        NEXT_PUBLIC_SANITY_PROJECT_ID: ${NEXT_PUBLIC_SANITY_PROJECT_ID}
        NEXT_PUBLIC_SANITY_DATASET: ${NEXT_PUBLIC_SANITY_DATASET}
        SANITY_API_READ_TOKEN: ${SANITY_API_READ_TOKEN}
    ports:
      - "3000:3000"
    networks:
      - smartcosme-network

networks:
  smartcosme-network:
    driver: bridge