import {
  Sun, Droplet, Leaf, Flame, Sparkles, Smile, Shield, Droplets, Flower, FlaskConical,
  Sprout, Filter, Feather, DropletIcon, Eye, DropletsIcon, RefreshCcw, Star, Heart, Wand, FlaskRound, PipetteIcon,
  Magnet,
  Ambulance,
  Bean,
  Waves,
  ShieldEllipsis,
  Grip,
  SwatchBook,
  BicepsFlexed,
  CircleDot,
  DropletOff,
  Sparkle,
  SprayCan,
  RollerCoaster,
  Kanban,
  ChartScatter,
  Blend,
  Building2,
  Coffee,
  Plane,
  Trees,
  Utensils,
  Calendar,
  MapPin,
  Luggage,
  Home,
  Truck,
  Stethoscope,
  Dog,
  BookOpen,
  Languages
} from "lucide-react";

export const iconMap: Record<string, React.ElementType> = {
  sun: Sun,
  droplet: Droplet,
  leaf: Leaf,
  flame: Flame,
  sparkles: Sparkles,
  sparkle: Sparkle,
  smile: Smile,
  shield: Shield,
  droplets: Droplets,
  flower: Flower,
  magnet: Magnet,
  ambulance: Ambulance,
  bean: Bean,
  flaskConical: FlaskConical,
  sprout: Sprout,
  filter: Filter,
  waves: Waves,
  shieldEllipsis: ShieldEllipsis,
  grip: Grip,
  swatch: SwatchBook,
  biceps: BicepsFlexed,
  circleDot: CircleDot,
  rollerCoaster: RollerCoaster,
  feather: Feather,
  dropletIcon: DropletIcon,
  eye: Eye,
  dropletsIcon: DropletsIcon,
  dropletsOff: DropletOff,
  refreshCcw: RefreshCcw,
  star: Star,
  kanban: Kanban,
  heart: Heart,
  chartScatter: ChartScatter,
  wand: Wand,
  blend: Blend,
  flaskRound: FlaskRound,
  pipetteIcon: PipetteIcon,
  sprayCan: SprayCan,
  hotel: Building2,
  coffee: Coffee,
  travel: Plane,
  park: Trees,
  restaurant: Utensils,
  weekend: Calendar,
  event: Calendar,
  map: MapPin,
  gear: Luggage,
  accommodation: Home,
  moving: Truck,
  services: Stethoscope,
  dogRun: Dog,
  stories: BookOpen,
  bilingual: Languages
};
